# Feed data to S3

The goal of this short exercise is to practise using `boto3` to communicate with the Amazon Data Lake service: S3.

The exercise is organized in two parts:
* Part one will have you upload a file from your local system directly to s3
* Part two will show you how to send files to your s3 that only exist as local python variables

## Part 1

1. Start by installing `boto3` if it has not been alrady

In [23]:
# Install boto3 using pip 
## Add '!' only if you install directly from a Jupyter Notebook
!pip install Boto3

Requirement already satisfied: Boto3 in /opt/conda/lib/python3.9/site-packages (1.21.23)
Requirement already satisfied: botocore<1.25.0,>=1.24.23 in /opt/conda/lib/python3.9/site-packages (from Boto3) (1.24.23)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.9/site-packages (from Boto3) (1.0.0)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in /opt/conda/lib/python3.9/site-packages (from Boto3) (0.5.2)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /opt/conda/lib/python3.9/site-packages (from botocore<1.25.0,>=1.24.23->Boto3) (1.26.8)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.9/site-packages (from botocore<1.25.0,>=1.24.23->Boto3) (2.8.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.9/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.25.0,>=1.24.23->Boto3) (1.16.0)

2. Import the necessary libraries

In [3]:
import json
import os
import pandas as pd
import boto3

3. Create an instance of `boto3.Session` that connects with your aws account.

In [4]:
session = boto3.Session()

4. Create a variable called `s3` that connects your session to the s3 ressource.

In [ ]:
s3 = boto3.client("s3", region_name="us-west-3")
s3 = session.resource("s3")

5. Create a variable called `bucket` that will connect to an existing bucket in your s3 or to a bucket you are creating now.

In [6]:
bucket = s3.create_bucket(
    Bucket="qha-feed-data-to-s3",
    CreateBucketConfiguration={
        "LocationConstraint": "eu-west-3"
    },
)

6. In the [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Bucket.upload_file), find a method that lets you upload files to your s3, and upload the file `crypto_data.json` to your bucket in the folder of your choice.

In [7]:
s3.Bucket("qha-feed-data-to-s3").upload_file("crypto_data.json", "crypto_data.json")

## Part 2

1. Using the `json` library, load the `crypto_data.json` file in a variable called `crypto`

In [ ]:
import requests

r = requests.get("https://qha-feed-data-to-s3.s3.eu-west-3.amazonaws.com/crypto_data.json")
crypto = json.loads(r.content)

print(json.dumps(crypto, indent=2))

{
  "btc-bitcoin": [
    {
      "time_open": "2012-01-01T00:00:00Z",
      "time_close": "2012-01-01T23:59:59Z",
      "open": 4.72,
      "high": 4.72,
      "low": 4.72,
      "close": 4.72
    },
    {
      "time_open": "2012-01-02T00:00:00Z",
      "time_close": "2012-01-02T23:59:59Z",
      "open": 5.27,
      "high": 5.27,
      "low": 5.27,
      "close": 5.27
    },
    {
      "time_open": "2012-01-03T00:00:00Z",
      "time_close": "2012-01-03T23:59:59Z",
      "open": 5.22,
      "high": 5.22,
      "low": 5.22,
      "close": 5.22
    },
    {
      "time_open": "2012-01-04T00:00:00Z",
      "time_close": "2012-01-04T23:59:59Z",
      "open": 4.88,
      "high": 4.88,
      "low": 4.88,
      "close": 4.88
    },
    {
      "time_open": "2012-01-05T00:00:00Z",
      "time_close": "2012-01-05T23:59:59Z",
      "open": 5.57,
      "high": 5.57,
      "low": 5.57,
      "close": 5.57
    },
    {
      "time_open": "2012-01-06T00:00:00Z",
      "time_close": "2012-01-06T23:59:59Z",
      "open": 6.95,
      "high": 6.95,
      "low": 6.95,
      "close": 6.95
    },
    {
      "time_open": "2012-01-07T00:00:00Z",
      "time_close": "2012-01-07T23:59:59Z",
      "open": 6.7,
      "high": 6.7,
      "low": 6.7,
      "close": 6.7
    },
    {
      "time_open": "2012-01-08T00:00:00Z",
      "time_close": "2012-01-08T23:59:59Z",
      "open": 6.81,
      "high": 6.81,
      "low": 6.81,
      "close": 6.81
    },
    {
      "time_open": "2012-01-09T00:00:00Z",
      "time_close": "2012-01-09T23:59:59Z",
      "open": 7.11,
      "high": 7.11,
      "low": 7.11,
      "close": 7.11
    },
    {
      "time_open": "2012-01-10T00:00:00Z",
      "time_close": "2012-01-10T23:59:59Z",
      "open": 6.33,
      "high": 6.33,
      "low": 6.33,
      "close": 6.33
    },
    {
      "time_open": "2012-01-11T00:00:00Z",
      "time_close": "2012-01-11T23:59:59Z",
      "open": 6.36,
      "high": 6.36,
      "low": 6.36,
      "close": 6.36
    },
    {
      "time_open": "2012-01-12T00:00:00Z",
      "time_close": "2012-01-12T23:59:59Z",
      "open": 6.9,
      "high": 6.9,
      "low": 6.9,
      "close": 6.9
    },
    {
      "time_open": "2012-01-13T00:00:00Z",
      "time_close": "2012-01-13T23:59:59Z",
      "open": 6.8,
      "high": 6.8,
      "low": 6.8,
      "close": 6.8
    },
    {
      "time_open": "2012-01-14T00:00:00Z",
      "time_close": "2012-01-14T23:59:59Z",
      "open": 6.41,
      "high": 6.41,
      "low": 6.41,
      "close": 6.41
    },
    {
      "time_open": "2012-01-15T00:00:00Z",
      "time_close": "2012-01-15T23:59:59Z",
      "open": 6.75,
      "high": 6.75,
      "low": 6.75,
      "close": 6.75
    },
    {
      "time_open": "2012-01-16T00:00:00Z",
      "time_close": "2012-01-16T23:59:59Z",
      "open": 7,
      "high": 7,
      "low": 7,
      "close": 7
    },
    {
      "time_open": "2012-01-17T00:00:00Z",
      "time_close": "2012-01-17T23:59:59Z",
      "open": 6.68,
      "high": 6.68,
      "low": 6.68,
      "close": 6.68
    },
    {
      "time_open": "2012-01-18T00:00:00Z",
      "time_close": "2012-01-18T23:59:59Z",
      "open": 5.6,
      "high": 5.6,
      "low": 5.6,
      "close": 5.6
    },
    {
      "time_open": "2012-01-19T00:00:00Z",
      "time_close": "2012-01-19T23:59:59Z",
      "open": 5.92,
      "high": 5.92,
      "low": 5.92,
      "close": 5.92
    },
    {
      "time_open": "2012-01-20T00:00:00Z",
      "time_close": "2012-01-20T23:59:59Z",
      "open": 6.36,
      "high": 6.36,
      "low": 6.36,
      "close": 6.36
    },
    {
      "time_open": "2012-01-21T00:00:00Z",
      "time_close": "2012-01-21T23:59:59Z",
      "open": 6.49,
      "high": 6.49,
      "low": 6.49,
      "close": 6.49
    },
    {
      "time_open": "2012-01-22T00:00:00Z",
      "time_close": "2012-01-22T23:59:59Z",
      "open": 6.18,
      "high": 6.18,
      "low": 6.18,
      "close": 6.18
    },
    {
      "time_open": "2012-01-23T00:00:00Z",
      "time_close": "2012-01-23T23:59:59Z",
      "open": 6.31,
      "high": 6.31,
      "low": 6.31,
      "close": 6.31
    },
    {
      "time_open": "2012-01-24T00:00:00Z",
      "time_close": "2012-01-24T23:59:59Z",
      "open": 6.36,
      "high": 6.36,
      "low": 6.36,
      "close": 6.36
    },
    {
      "time_open": "2012-01-25T00:00:00Z",
      "time_close": "2012-01-25T23:59:59Z",
      "open": 6.29,
      "high": 6.29,
      "low": 6.29,
      "close": 6.29
    },
    {
      "time_open": "2012-01-26T00:00:00Z",
      "time_close": "2012-01-26T23:59:59Z",
      "open": 5.75,
      "high": 5.75,
      "low": 5.75,
      "close": 5.75
    },
    {
      "time_open": "2012-01-27T00:00:00Z",
      "time_close": "2012-01-27T23:59:59Z",
      "open": 5.34,
      "high": 5.34,
      "low": 5.34,
      "close": 5.34
    },
    {
      "time_open": "2012-01-28T00:00:00Z",
      "time_close": "2012-01-28T23:59:59Z",
      "open": 5.29,
      "high": 5.29,
      "low": 5.29,
      "close": 5.29
    },
    {
      "time_open": "2012-01-29T00:00:00Z",
      "time_close": "2012-01-29T23:59:59Z",
      "open": 5.63,
      "high": 5.63,
      "low": 5.63,
      "close": 5.63
    },
    {
      "time_open": "2012-01-30T00:00:00Z",
      "time_close": "2012-01-30T23:59:59Z",
      "open": 5.38,
      "high": 5.38,
      "low": 5.38,
      "close": 5.38
    },
    {
      "time_open": "2012-01-31T00:00:00Z",
      "time_close": "2012-01-31T23:59:59Z",
      "open": 5.49,
      "high": 5.49,
      "low": 5.49,
      "close": 5.49
    },
    {
      "time_open": "2012-02-01T00:00:00Z",
      "time_close": "2012-02-01T23:59:59Z",
      "open": 5.48,
      "high": 5.48,
      "low": 5.48,
      "close": 5.48
    },
    {
      "time_open": "2012-02-02T00:00:00Z",
      "time_close": "2012-02-02T23:59:59Z",
      "open": 6.08,
      "high": 6.08,
      "low": 6.08,
      "close": 6.08
    },
    {
      "time_open": "2012-02-03T00:00:00Z",
      "time_close": "2012-02-03T23:59:59Z",
      "open": 6.1,
      "high": 6.1,
      "low": 6.1,
      "close": 6.1
    },
    {
      "time_open": "2012-02-04T00:00:00Z",
      "time_close": "2012-02-04T23:59:59Z",
      "open": 5.96,
      "high": 5.96,
      "low": 5.96,
      "close": 5.96
    },
    {
      "time_open": "2012-02-05T00:00:00Z",
      "time_close": "2012-02-05T23:59:59Z",
      "open": 5.87,
      "high": 5.87,
      "low": 5.87,
      "close": 5.87
    },
    {
      "time_open": "2012-02-06T00:00:00Z",
      "time_close": "2012-02-06T23:59:59Z",
      "open": 5.69,
      "high": 5.69,
      "low": 5.69,
      "close": 5.69
    },
    {
      "time_open": "2012-02-07T00:00:00Z",
      "time_close": "2012-02-07T23:59:59Z",
      "open": 5.45,
      "high": 5.45,
      "low": 5.45,
      "close": 5.45
    },
    {
      "time_open": "2012-02-08T00:00:00Z",
      "time_close": "2012-02-08T23:59:59Z",
      "open": 5.69,
      "high": 5.69,
      "low": 5.69,
      "close": 5.69
    },
    {
      "time_open": "2012-02-09T00:00:00Z",
      "time_close": "2012-02-09T23:59:59Z",
      "open": 5.6,
      "high": 5.6,
      "low": 5.6,
      "close": 5.6
    },
    {
      "time_open": "2012-02-10T00:00:00Z",
      "time_close": "2012-02-10T23:59:59Z",
      "open": 5.83,
      "high": 5.83,
      "low": 5.83,
      "close": 5.83
    },
    {
      "time_open": "2012-02-11T00:00:00Z",
      "time_close": "2012-02-11T23:59:59Z",
      "open": 5.91,
      "high": 5.91,
      "low": 5.91,
      "close": 5.91
    },
    {
      "time_open": "2012-02-12T00:00:00Z",
      "time_close": "2012-02-12T23:59:59Z",
      "open": 5.6,
      "high": 5.6,
      "low": 5.6,
      "close": 5.6
    },
    {
      "time_open": "2012-02-13T00:00:00Z",
      "time_close": "2012-02-13T23:59:59Z",
      "open": 5.51,
      "high": 5.51,
      "low": 5.51,
      "close": 5.51
    },
    {
      "time_open": "2012-02-14T00:00:00Z",
      "time_close": "2012-02-14T23:59:59Z",
      "open": 5.26,
      "high": 5.26,
      "low": 5.26,
      "close": 5.26
    },
    {
      "time_open": "2012-02-15T00:00:00Z",
      "time_close": "2012-02-15T23:59:59Z",
      "open": 4.46,
      "high": 4.46,
      "low": 4.46,
      "close": 4.46
    },
    {
      "time_open": "2012-02-16T00:00:00Z",
      "time_close": "2012-02-16T23:59:59Z",
      "open": 4.33,
      "high": 4.33,
      "low": 4.33,
      "close": 4.33
    },
    {
      "time_open": "2012-02-17T00:00:00Z",
      "time_close": "2012-02-17T23:59:59Z",
      "open": 4.27,
      "high": 4.27,
      "low": 4.27,
      "close": 4.27
    },
    {
      "time_open": "2012-02-18T00:00:00Z",
      "time_close": "2012-02-18T23:59:59Z",
      "open": 4.41,
      "high": 4.41,
      "low": 4.41,
      "close": 4.41
    },
    {
      "time_open": "2012-02-19T00:00:00Z",
      "time_close": "2012-02-19T23:59:59Z",
      "open": 4.22,
      "high": 4.22,
      "low": 4.22,
      "close": 4.22
    },
    {
      "time_open": "2012-02-20T00:00:00Z",
      "time_close": "2012-02-20T23:59:59Z",
      "open": 4.39,
      "high": 4.39,
      "low": 4.39,
      "close": 4.39
    },
    {
      "time_open": "2012-02-21T00:00:00Z",
      "time_close": "2012-02-21T23:59:59Z",
      "open": 4.36,
      "high": 4.36,
      "low": 4.36,
      "close": 4.36
    },
    {
      "time_open": "2012-02-22T00:00:00Z",
      "time_close": "2012-02-22T23:59:59Z",
      "open": 4.27,
      "high": 4.27,
      "low": 4.27,
      "close": 4.27
    },
    {
      "time_open": "2012-02-23T00:00:00Z",
      "time_close": "2012-02-23T23:59:59Z",
      "open": 4.42,
      "high": 4.42,
      "low": 4.42,
      "close": 4.42
    },
    {
      "time_open": "2012-02-24T00:00:00Z",
      "time_close": "2012-02-24T23:59:59Z",
      "open": 5.01,
      "high": 5.01,
      "low": 5.01,
      "close": 5.01
    },
    {
      "time_open": "2012-02-25T00:00:00Z",
      "time_close": "2012-02-25T23:59:59Z",
      "open": 5.03,
      "high": 5.03,
      "low": 5.03,
      "close": 5.03
    },
    {
      "time_open": "2012-02-26T00:00:00Z",
      "time_close": "2012-02-26T23:59:59Z",
      "open": 4.77,
      "high": 4.77,
      "low": 4.77,
      "close": 4.77
    },
    {
      "time_open": "2012-02-27T00:00:00Z",
      "time_close": "2012-02-27T23:59:59Z",
      "open": 4.92,
      "high": 4.92,
      "low": 4.92,
      "close": 4.92
    },
    {
      "time_open": "2012-02-28T00:00:00Z",
      "time_close": "2012-02-28T23:59:59Z",
      "open": 4.96,
      "high": 4.96,
      "low": 4.96,
      "close": 4.96
    },
    {
      "time_open": "2012-02-29T00:00:00Z",
      "time_close": "2012-02-29T23:59:59Z",
      "open": 4.87,
      "high": 4.87,
      "low": 4.87,
      "close": 4.87
    },
    {
      "time_open": "2012-03-01T00:00:00Z",
      "time_close": "2012-03-01T23:59:59Z",
      "open": 4.86,
      "high": 4.86,
      "low": 4.86,
      "close": 4.86
    },
    {
      "time_open": "2012-03-02T00:00:00Z",
      "time_close": "2012-03-02T23:59:59Z",
      "open": 4.92,
      "high": 4.92,
      "low": 4.92,
      "close": 4.92
    },
    {
      "time_open": "2012-03-03T00:00:00Z",
      "time_close": "2012-03-03T23:59:59Z",
      "open": 4.7,
      "high": 4.7,
      "low": 4.7,
      "close": 4.7
    },
    {
      "time_open": "2012-03-04T00:00:00Z",
      "time_close": "2012-03-04T23:59:59Z",
      "open": 4.61,
      "high": 4.61,
      "low": 4.61,
      "close": 4.61
    },
    {
      "time_open": "2012-03-05T00:00:00Z",
      "time_close": "2012-03-05T23:59:59Z",
      "open": 4.82,
      "high": 4.82,
      "low": 4.82,
      "close": 4.82
    },
    {
      "time_open": "2012-03-06T00:00:00Z",
      "time_close": "2012-03-06T23:59:59Z",
      "open": 4.98,
      "high": 4.98,
      "low": 4.98,
      "close": 4.98
    },
    {
      "time_open": "2012-03-07T00:00:00Z",
      "time_close": "2012-03-07T23:59:59Z",
      "open": 4.99,
      "high": 4.99,
      "low": 4.99,
      "close": 4.99
    },
    {
      "time_open": "2012-03-08T00:00:00Z",
      "time_close": "2012-03-08T23:59:59Z",
      "open": 4.94,
      "high": 4.94,
      "low": 4.94,
      "close": 4.94
    },
    {
      "time_open": "2012-03-09T00:00:00Z",
      "time_close": "2012-03-09T23:59:59Z",
      "open": 4.93,
      "high": 4.93,
      "low": 4.93,
      "close": 4.93
    },
    {
      "time_open": "2012-03-10T00:00:00Z",
      "time_close": "2012-03-10T23:59:59Z",
      "open": 4.86,
      "high": 4.86,
      "low": 4.86,
      "close": 4.86
    },
    {
      "time_open": "2012-03-11T00:00:00Z",
      "time_close": "2012-03-11T23:59:59Z",
      "open": 4.83,
      "high": 4.83,
      "low": 4.83,
      "close": 4.83
    },
    {
      "time_open": "2012-03-12T00:00:00Z",
      "time_close": "2012-03-12T23:59:59Z",
      "open": 4.91,
      "high": 4.91,
      "low": 4.91,
      "close": 4.91
    },
    {
      "time_open": "2012-03-13T00:00:00Z",
      "time_close": "2012-03-13T23:59:59Z",
      "open": 4.89,
      "high": 4.89,
      "low": 4.89,
      "close": 4.89
    },
    {
      "time_open": "2012-03-14T00:00:00Z",
      "time_close": "2012-03-14T23:59:59Z",
      "open": 5.27,
      "high": 5.27,
      "low": 5.27,
      "close": 5.27
    },
    {
      "time_open": "2012-03-15T00:00:00Z",
      "time_close": "2012-03-15T23:59:59Z",
      "open": 5.38,
      "high": 5.38,
      "low": 5.38,
      "close": 5.38
    },
    {
      "time_open": "2012-03-16T00:00:00Z",
      "time_close": "2012-03-16T23:59:59Z",
      "open": 5.33,
      "high": 5.33,
      "low": 5.33,
      "close": 5.33
    },
    {
      "time_open": "2012-03-17T00:00:00Z",
      "time_close": "2012-03-17T23:59:59Z",
      "open": 5.34,
      "high": 5.34,
      "low": 5.34,
      "close": 5.34
    },
    {
      "time_open": "2012-03-18T00:00:00Z",
      "time_close": "2012-03-18T23:59:59Z",
      "open": 5.22,
      "high": 5.22,
      "low": 5.22,
      "close": 5.22
    },
    {
      "time_open": "2012-03-19T00:00:00Z",
      "time_close": "2012-03-19T23:59:59Z",
      "open": 5.28,
      "high": 5.28,
      "low": 5.28,
      "close": 5.28
    },
    {
      "time_open": "2012-03-20T00:00:00Z",
      "time_close": "2012-03-20T23:59:59Z",
      "open": 4.69,
      "high": 4.69,
      "low": 4.69,
      "close": 4.69
    },
    {
      "time_open": "2012-03-21T00:00:00Z",
      "time_close": "2012-03-21T23:59:59Z",
      "open": 4.84,
      "high": 4.84,
      "low": 4.84,
      "close": 4.84
    },
    {
      "time_open": "2012-03-22T00:00:00Z",
      "time_close": "2012-03-22T23:59:59Z",
      "open": 4.81,
      "high": 4.81,
      "low": 4.81,
      "close": 4.81
    },
    {
      "time_open": "2012-03-23T00:00:00Z",
      "time_close": "2012-03-23T23:59:59Z",
      "open": 4.7,
      "high": 4.7,
      "low": 4.7,
      "close": 4.7
    },
    {
      "time_open": "2012-03-24T00:00:00Z",
      "time_close": "2012-03-24T23:59:59Z",
      "open": 4.69,
      "high": 4.69,
      "low": 4.69,
      "close": 4.69
    },
    {
      "time_open": "2012-03-25T00:00:00Z",
      "time_close": "2012-03-25T23:59:59Z",
      "open": 4.68,
      "high": 4.68,
      "low": 4.68,
      "close": 4.68
    },
    {
      "time_open": "2012-03-26T00:00:00Z",
      "time_close": "2012-03-26T23:59:59Z",
      "open": 4.55,
      "high": 4.55,
      "low": 4.55,
      "close": 4.55
    },
    {
      "time_open": "2012-03-27T00:00:00Z",
      "time_close": "2012-03-27T23:59:59Z",
      "open": 4.62,
      "high": 4.62,
      "low": 4.62,
      "close": 4.62
    },
    {
      "time_open": "2012-03-28T00:00:00Z",
      "time_close": "2012-03-28T23:59:59Z",
      "open": 4.81,
      "high": 4.81,
      "low": 4.81,
      "close": 4.81
    },
    {
      "time_open": "2012-03-29T00:00:00Z",
      "time_close": "2012-03-29T23:59:59Z",
      "open": 4.79,
      "high": 4.79,
      "low": 4.79,
      "close": 4.79
    },
    {
      "time_open": "2012-03-30T00:00:00Z",
      "time_close": "2012-03-30T23:59:59Z",
      "open": 4.81,
      "high": 4.81,
      "low": 4.81,
      "close": 4.81
    },
    {
      "time_open": "2012-03-31T00:00:00Z",
      "time_close": "2012-03-31T23:59:59Z",
      "open": 4.86,
      "high": 4.86,
      "low": 4.86,
      "close": 4.86
    },
    {
      "time_open": "2012-04-01T00:00:00Z",
      "time_close": "2012-04-01T23:59:59Z",
      "open": 4.91,
      "high": 4.91,
      "low": 4.91,
      "close": 4.91
    },
    {
      "time_open": "2012-04-02T00:00:00Z",
      "time_close": "2012-04-02T23:59:59Z",
      "open": 4.83,
      "high": 4.83,
      "low": 4.83,
      "close": 4.83
    },
    {
      "time_open": "2012-04-03T00:00:00Z",
      "time_close": "2012-04-03T23:59:59Z",
      "open": 4.97,
      "high": 4.97,
      "low": 4.97,
      "close": 4.97
    },
    {
      "time_open": "2012-04-04T00:00:00Z",
      "time_close": "2012-04-04T23:59:59Z",
      "open": 4.95,
      "high": 4.95,
      "low": 4.95,
      "close": 4.95
    },
    {
      "time_open": "2012-04-05T00:00:00Z",
      "time_close": "2012-04-05T23:59:59Z",
      "open": 4.91,
      "high": 4.91,
      "low": 4.91,
      "close": 4.91
    },
    {
      "time_open": "2012-04-06T00:00:00Z",
      "time_close": "2012-04-06T23:59:59Z",
      "open": 4.92,
      "high": 4.92,
      "low": 4.92,
      "close": 4.92
    },
    {
      "time_open": "2012-04-07T00:00:00Z",
      "time_close": "2012-04-07T23:59:59Z",
      "open": 4.95,
      "high": 4.95,
      "low": 4.95,
      "close": 4.95
    },
    {
      "time_open": "2012-04-08T00:00:00Z",
      "time_close": "2012-04-08T23:59:59Z",
      "open": 4.69,
      "high": 4.69,
      "low": 4.69,
      "close": 4.69
    },
    {
      "time_open": "2012-04-09T00:00:00Z",
      "time_close": "2012-04-09T23:59:59Z",
      "open": 4.79,
      "high": 4.79,
      "low": 4.79,
      "close": 4.79
    },
    {
      "time_open": "2012-04-10T00:00:00Z",
      "time_close": "2012-04-10T23:59:59Z",
      "open": 4.87,
      "high": 4.87,
      "low": 4.87,
      "close": 4.87
    },
    {
      "time_open": "2012-04-11T00:00:00Z",
      "time_close": "2012-04-11T23:59:59Z",
      "open": 4.84,
      "high": 4.84,
      "low": 4.84,
      "close": 4.84
    },
    {
      "time_open": "2012-04-12T00:00:00Z",
      "time_close": "2012-04-12T23:59:59Z",
      "open": 4.93,
      "high": 4.93,
      "low": 4.93,
      "close": 4.93
    },
    {
      "time_open": "2012-04-13T00:00:00Z",
      "time_close": "2012-04-13T23:59:59Z",
      "open": 4.92,
      "high": 4.92,
      "low": 4.92,
      "close": 4.92
    },
    {
      "time_open": "2012-04-14T00:00:00Z",
      "time_close": "2012-04-14T23:59:59Z",
      "open": 4.94,
      "high": 4.94,
      "low": 4.94,
      "close": 4.94
    },
    {
      "time_open": "2012-04-15T00:00:00Z",
      "time_close": "2012-04-15T23:59:59Z",
      "open": 4.96,
      "high": 4.96,
      "low": 4.96,
      "close": 4.96
    },
    {
      "time_open": "2012-04-16T00:00:00Z",
      "time_close": "2012-04-16T23:59:59Z",
      "open": 4.97,
      "high": 4.97,
      "low": 4.97,
      "close": 4.97
    },
    {
      "time_open": "2012-04-17T00:00:00Z",
      "time_close": "2012-04-17T23:59:59Z",
      "open": 4.93,
      "high": 4.93,
      "low": 4.93,
      "close": 4.93
    },
    {
      "time_open": "2012-04-18T00:00:00Z",
      "time_close": "2012-04-18T23:59:59Z",
      "open": 4.98,
      "high": 4.98,
      "low": 4.98,
      "close": 4.98
    },
    {
      "time_open": "2012-04-19T00:00:00Z",
      "time_close": "2012-04-19T23:59:59Z",
      "open": 5.12,
      "high": 5.12,
      "low": 5.12,
      "close": 5.12
    },
    {
      "time_open": "2012-04-20T00:00:00Z",
      "time_close": "2012-04-20T23:59:59Z",
      "open": 5.14,
      "high": 5.14,
      "low": 5.14,
      "close": 5.14
    },
    {
      "time_open": "2012-04-21T00:00:00Z",
      "time_close": "2012-04-21T23:59:59Z",
      "open": 5.35,
      "high": 5.35,
      "low": 5.35,

2. What is the type of variable `crypto`

In [16]:
type(crypto)

dict

3. Display the different possible keys in `crypto` in the form of a list

In [23]:
crypto_name = list(crypto.keys())
crypto_name

['btc-bitcoin',
 'eth-ethereum',
 'usdt-tether',
 'bnb-binance-coin',
 'hex-hex',
 'usdc-usd-coin',
 'ada-cardano',
 'sol-solana',
 'xrp-xrp',
 'luna-terra']

4. Have a look at the value associated with the first key, do you think it could easily be converted to a pandas DataFrame?

In [24]:
first_crypto = crypto[crypto_name[0]]
first_crypto

[{'time_open': '2012-01-01T00:00:00Z',
  'time_close': '2012-01-01T23:59:59Z',
  'open': 4.72,
  'high': 4.72,
  'low': 4.72,
  'close': 4.72},
 {'time_open': '2012-01-02T00:00:00Z',
  'time_close': '2012-01-02T23:59:59Z',
  'open': 5.27,
  'high': 5.27,
  'low': 5.27,
  'close': 5.27},
 {'time_open': '2012-01-03T00:00:00Z',
  'time_close': '2012-01-03T23:59:59Z',
  'open': 5.22,
  'high': 5.22,
  'low': 5.22,
  'close': 5.22},
 {'time_open': '2012-01-04T00:00:00Z',
  'time_close': '2012-01-04T23:59:59Z',
  'open': 4.88,
  'high': 4.88,
  'low': 4.88,
  'close': 4.88},
 {'time_open': '2012-01-05T00:00:00Z',
  'time_close': '2012-01-05T23:59:59Z',
  'open': 5.57,
  'high': 5.57,
  'low': 5.57,
  'close': 5.57},
 {'time_open': '2012-01-06T00:00:00Z',
  'time_close': '2012-01-06T23:59:59Z',
  'open': 6.95,
  'high': 6.95,
  'low': 6.95,
  'close': 6.95},
 {'time_open': '2012-01-07T00:00:00Z',
  'time_close': '2012-01-07T23:59:59Z',
  'open': 6.7,
  'high': 6.7,
  'low': 6.7,
  'close': 6.7},
 {'time_open': '2012-01-08T00:00:00Z',
  'time_close': '2012-01-08T23:59:59Z',
  'open': 6.81,
  'high': 6.81,
  'low': 6.81,
  'close': 6.81},
 {'time_open': '2012-01-09T00:00:00Z',
  'time_close': '2012-01-09T23:59:59Z',
  'open': 7.11,
  'high': 7.11,
  'low': 7.11,
  'close': 7.11},
 {'time_open': '2012-01-10T00:00:00Z',
  'time_close': '2012-01-10T23:59:59Z',
  'open': 6.33,
  'high': 6.33,
  'low': 6.33,
  'close': 6.33},
 {'time_open': '2012-01-11T00:00:00Z',
  'time_close': '2012-01-11T23:59:59Z',
  'open': 6.36,
  'high': 6.36,
  'low': 6.36,
  'close': 6.36},
 {'time_open': '2012-01-12T00:00:00Z',
  'time_close': '2012-01-12T23:59:59Z',
  'open': 6.9,
  'high': 6.9,
  'low': 6.9,
  'close': 6.9},
 {'time_open': '2012-01-13T00:00:00Z',
  'time_close': '2012-01-13T23:59:59Z',
  'open': 6.8,
  'high': 6.8,
  'low': 6.8,
  'close': 6.8},
 {'time_open': '2012-01-14T00:00:00Z',
  'time_close': '2012-01-14T23:59:59Z',
  'open': 6.41,
  'high': 6.41,
  'low': 6.41,
  'close': 6.41},
 {'time_open': '2012-01-15T00:00:00Z',
  'time_close': '2012-01-15T23:59:59Z',
  'open': 6.75,
  'high': 6.75,
  'low': 6.75,
  'close': 6.75},
 {'time_open': '2012-01-16T00:00:00Z',
  'time_close': '2012-01-16T23:59:59Z',
  'open': 7,
  'high': 7,
  'low': 7,
  'close': 7},
 {'time_open': '2012-01-17T00:00:00Z',
  'time_close': '2012-01-17T23:59:59Z',
  'open': 6.68,
  'high': 6.68,
  'low': 6.68,
  'close': 6.68},
 {'time_open': '2012-01-18T00:00:00Z',
  'time_close': '2012-01-18T23:59:59Z',
  'open': 5.6,
  'high': 5.6,
  'low': 5.6,
  'close': 5.6},
 {'time_open': '2012-01-19T00:00:00Z',
  'time_close': '2012-01-19T23:59:59Z',
  'open': 5.92,
  'high': 5.92,
  'low': 5.92,
  'close': 5.92},
 {'time_open': '2012-01-20T00:00:00Z',
  'time_close': '2012-01-20T23:59:59Z',
  'open': 6.36,
  'high': 6.36,
  'low': 6.36,
  'close': 6.36},
 {'time_open': '2012-01-21T00:00:00Z',
  'time_close': '2012-01-21T23:59:59Z',
  'open': 6.49,
  'high': 6.49,
  'low': 6.49,
  'close': 6.49},
 {'time_open': '2012-01-22T00:00:00Z',
  'time_close': '2012-01-22T23:59:59Z',
  'open': 6.18,
  'high': 6.18,
  'low': 6.18,
  'close': 6.18},
 {'time_open': '2012-01-23T00:00:00Z',
  'time_close': '2012-01-23T23:59:59Z',
  'open': 6.31,
  'high': 6.31,
  'low': 6.31,
  'close': 6.31},
 {'time_open': '2012-01-24T00:00:00Z',
  'time_close': '2012-01-24T23:59:59Z',
  'open': 6.36,
  'high': 6.36,
  'low': 6.36,
  'close': 6.36},
 {'time_open': '2012-01-25T00:00:00Z',
  'time_close': '2012-01-25T23:59:59Z',
  'open': 6.29,
  'high': 6.29,
  'low': 6.29,
  'close': 6.29},
 {'time_open': '2012-01-26T00:00:00Z',
  'time_close': '2012-01-26T23:59:59Z',
  'open': 5.75,
  'high': 5.75,
  'low': 5.75,
  'close': 5.75},
 {'time_open': '2012-01-27T00:00:00Z',
  'time_close': '2012-01-27T23:59:59Z',
  'open': 5.34,
  'high': 5.34,
  'low': 5.34,
  'close': 5.34},
 {'time_open': '2012-01-28T00:00:00Z',
  'time_close': '2012-01-28T23:59:59Z',
  'open': 5.29,
  'high': 5.29,
  'low': 5.29,
  'close': 5.29},
 {'time_open': '2012-01-29T00:00:00Z',
  'time_close': '2012-01-29T23:59:59Z',
  'open': 5.63,
  'high': 5.63,
  'low': 5.63,
  'close': 5.63},
 {'time_open': '2012-01-30T00:00:00Z',
  'time_close': '2012-01-30T23:59:59Z',
  'open': 5.38,
  'high': 5.38,
  'low': 5.38,
  'close': 5.38},
 {'time_open': '2012-01-31T00:00:00Z',
  'time_close': '2012-01-31T23:59:59Z',
  'open': 5.49,
  'high': 5.49,
  'low': 5.49,
  'close': 5.49},
 {'time_open': '2012-02-01T00:00:00Z',
  'time_close': '2012-02-01T23:59:59Z',
  'open': 5.48,
  'high': 5.48,
  'low': 5.48,
  'close': 5.48},
 {'time_open': '2012-02-02T00:00:00Z',
  'time_close': '2012-02-02T23:59:59Z',
  'open': 6.08,
  'high': 6.08,
  'low': 6.08,
  'close': 6.08},
 {'time_open': '2012-02-03T00:00:00Z',
  'time_close': '2012-02-03T23:59:59Z',
  'open': 6.1,
  'high': 6.1,
  'low': 6.1,
  'close': 6.1},
 {'time_open': '2012-02-04T00:00:00Z',
  'time_close': '2012-02-04T23:59:59Z',
  'open': 5.96,
  'high': 5.96,
  'low': 5.96,
  'close': 5.96},
 {'time_open': '2012-02-05T00:00:00Z',
  'time_close': '2012-02-05T23:59:59Z',
  'open': 5.87,
  'high': 5.87,
  'low': 5.87,
  'close': 5.87},
 {'time_open': '2012-02-06T00:00:00Z',
  'time_close': '2012-02-06T23:59:59Z',
  'open': 5.69,
  'high': 5.69,
  'low': 5.69,
  'close': 5.69},
 {'time_open': '2012-02-07T00:00:00Z',
  'time_close': '2012-02-07T23:59:59Z',
  'open': 5.45,
  'high': 5.45,
  'low': 5.45,
  'close': 5.45},
 {'time_open': '2012-02-08T00:00:00Z',
  'time_close': '2012-02-08T23:59:59Z',
  'open': 5.69,
  'high': 5.69,
  'low': 5.69,
  'close': 5.69},
 {'time_open': '2012-02-09T00:00:00Z',
  'time_close': '2012-02-09T23:59:59Z',
  'open': 5.6,
  'high': 5.6,
  'low': 5.6,
  'close': 5.6},
 {'time_open': '2012-02-10T00:00:00Z',
  'time_close': '2012-02-10T23:59:59Z',
  'open': 5.83,
  'high': 5.83,
  'low': 5.83,
  'close': 5.83},
 {'time_open': '2012-02-11T00:00:00Z',
  'time_close': '2012-02-11T23:59:59Z',
  'open': 5.91,
  'high': 5.91,
  'low': 5.91,
  'close': 5.91},
 {'time_open': '2012-02-12T00:00:00Z',
  'time_close': '2012-02-12T23:59:59Z',
  'open': 5.6,
  'high': 5.6,
  'low': 5.6,
  'close': 5.6},
 {'time_open': '2012-02-13T00:00:00Z',
  'time_close': '2012-02-13T23:59:59Z',
  'open': 5.51,
  'high': 5.51,
  'low': 5.51,
  'close': 5.51},
 {'time_open': '2012-02-14T00:00:00Z',
  'time_close': '2012-02-14T23:59:59Z',
  'open': 5.26,
  'high': 5.26,
  'low': 5.26,
  'close': 5.26},
 {'time_open': '2012-02-15T00:00:00Z',
  'time_close': '2012-02-15T23:59:59Z',
  'open': 4.46,
  'high': 4.46,
  'low': 4.46,
  'close': 4.46},
 {'time_open': '2012-02-16T00:00:00Z',
  'time_close': '2012-02-16T23:59:59Z',
  'open': 4.33,
  'high': 4.33,
  'low': 4.33,
  'close': 4.33},
 {'time_open': '2012-02-17T00:00:00Z',
  'time_close': '2012-02-17T23:59:59Z',
  'open': 4.27,
  'high': 4.27,
  'low': 4.27,
  'close': 4.27},
 {'time_open': '2012-02-18T00:00:00Z',
  'time_close': '2012-02-18T23:59:59Z',
  'open': 4.41,
  'high': 4.41,
  'low': 4.41,
  'close': 4.41},
 {'time_open': '2012-02-19T00:00:00Z',
  'time_close': '2012-02-19T23:59:59Z',
  'open': 4.22,
  'high': 4.22,
  'low': 4.22,
  'close': 4.22},
 {'time_open': '2012-02-20T00:00:00Z',
  'time_close': '2012-02-20T23:59:59Z',
  'open': 4.39,
  'high': 4.39,
  'low': 4.39,
  'close': 4.39},
 {'time_open': '2012-02-21T00:00:00Z',
  'time_close': '2012-02-21T23:59:59Z',
  'open': 4.36,
  'high': 4.36,
  'low': 4.36,
  'close': 4.36},
 {'time_open': '2012-02-22T00:00:00Z',
  'time_close': '2012-02-22T23:59:59Z',
  'open': 4.27,
  'high': 4.27,
  'low': 4.27,
  'close': 4.27},
 {'time_open': '2012-02-23T00:00:00Z',
  'time_close': '2012-02-23T23:59:59Z',
  'open': 4.42,
  'high': 4.42,
  'low': 4.42,
  'close': 4.42},
 {'time_open': '2012-02-24T00:00:00Z',
  'time_close': '2012-02-24T23:59:59Z',
  'open': 5.01,
  'high': 5.01,
  'low': 5.01,
  'close': 5.01},
 {'time_open': '2012-02-25T00:00:00Z',
  'time_close': '2012-02-25T23:59:59Z',
  'open': 5.03,
  'high': 5.03,
  'low': 5.03,
  'close': 5.03},
 {'time_open': '2012-02-26T00:00:00Z',
  'time_close': '2012-02-26T23:59:59Z',
  'open': 4.77,
  'high': 4.77,
  'low': 4.77,
  'close': 4.77},
 {'time_open': '2012-02-27T00:00:00Z',
  'time_close': '2012-02-27T23:59:59Z',
  'open': 4.92,
  'high': 4.92,
  'low': 4.92,
  'close': 4.92},
 {'time_open': '2012-02-28T00:00:00Z',
  'time_close': '2012-02-28T23:59:59Z',
  'open': 4.96,
  'high': 4.96,
  'low': 4.96,
  'close': 4.96},
 {'time_open': '2012-02-29T00:00:00Z',
  'time_close': '2012-02-29T23:59:59Z',
  'open': 4.87,
  'high': 4.87,
  'low': 4.87,
  'close': 4.87},
 {'time_open': '2012-03-01T00:00:00Z',
  'time_close': '2012-03-01T23:59:59Z',
  'open': 4.86,
  'high': 4.86,
  'low': 4.86,
  'close': 4.86},
 {'time_open': '2012-03-02T00:00:00Z',
  'time_close': '2012-03-02T23:59:59Z',
  'open': 4.92,
  'high': 4.92,
  'low': 4.92,
  'close': 4.92},
 {'time_open': '2012-03-03T00:00:00Z',
  'time_close': '2012-03-03T23:59:59Z',
  'open': 4.7,
  'high': 4.7,
  'low': 4.7,
  'close': 4.7},
 {'time_open': '2012-03-04T00:00:00Z',
  'time_close': '2012-03-04T23:59:59Z',
  'open': 4.61,
  'high': 4.61,
  'low': 4.61,
  'close': 4.61},
 {'time_open': '2012-03-05T00:00:00Z',
  'time_close': '2012-03-05T23:59:59Z',
  'open': 4.82,
  'high': 4.82,
  'low': 4.82,
  'close': 4.82},
 {'time_open': '2012-03-06T00:00:00Z',
  'time_close': '2012-03-06T23:59:59Z',
  'open': 4.98,
  'high': 4.98,
  'low': 4.98,
  'close': 4.98},
 {'time_open': '2012-03-07T00:00:00Z',
  'time_close': '2012-03-07T23:59:59Z',
  'open': 4.99,
  'high': 4.99,
  'low': 4.99,
  'close': 4.99},
 {'time_open': '2012-03-08T00:00:00Z',
  'time_close': '2012-03-08T23:59:59Z',
  'open': 4.94,
  'high': 4.94,
  'low': 4.94,
  'close': 4.94},
 {'time_open': '2012-03-09T00:00:00Z',
  'time_close': '2012-03-09T23:59:59Z',
  'open': 4.93,
  'high': 4.93,
  'low': 4.93,
  'close': 4.93},
 {'time_open': '2012-03-10T00:00:00Z',
  'time_close': '2012-03-10T23:59:59Z',
  'open': 4.86,
  'high': 4.86,
  'low': 4.86,
  'close': 4.86},
 {'time_open': '2012-03-11T00:00:00Z',
  'time_close': '2012-03-11T23:59:59Z',
  'open': 4.83,
  'high': 4.83,
  'low': 4.83,
  'close': 4.83},
 {'time_open': '2012-03-12T00:00:00Z',
  'time_close': '2012-03-12T23:59:59Z',
  'open': 4.91,
  'high': 4.91,
  'low': 4.91,
  'close': 4.91},
 {'time_open': '2012-03-13T00:00:00Z',
  'time_close': '2012-03-13T23:59:59Z',
  'open': 4.89,
  'high': 4.89,
  'low': 4.89,
  'close': 4.89},
 {'time_open': '2012-03-14T00:00:00Z',
  'time_close': '2012-03-14T23:59:59Z',
  'open': 5.27,
  'high': 5.27,
  'low': 5.27,
  'close': 5.27},
 {'time_open': '2012-03-15T00:00:00Z',
  'time_close': '2012-03-15T23:59:59Z',
  'open': 5.38,
  'high': 5.38,
  'low': 5.38,
  'close': 5.38},
 {'time_open': '2012-03-16T00:00:00Z',
  'time_close': '2012-03-16T23:59:59Z',
  'open': 5.33,
  'high': 5.33,
  'low': 5.33,
  'close': 5.33},
 {'time_open': '2012-03-17T00:00:00Z',
  'time_close': '2012-03-17T23:59:59Z',
  'open': 5.34,
  'high': 5.34,
  'low': 5.34,
  'close': 5.34},
 {'time_open': '2012-03-18T00:00:00Z',
  'time_close': '2012-03-18T23:59:59Z',
  'open': 5.22,
  'high': 5.22,
  'low': 5.22,
  'close': 5.22},
 {'time_open': '2012-03-19T00:00:00Z',
  'time_close': '2012-03-19T23:59:59Z',
  'open': 5.28,
  'high': 5.28,
  'low': 5.28,
  'close': 5.28},
 {'time_open': '2012-03-20T00:00:00Z',
  'time_close': '2012-03-20T23:59:59Z',
  'open': 4.69,
  'high': 4.69,
  'low': 4.69,
  'close': 4.69},
 {'time_open': '2012-03-21T00:00:00Z',
  'time_close': '2012-03-21T23:59:59Z',
  'open': 4.84,
  'high': 4.84,
  'low': 4.84,
  'close': 4.84},
 {'time_open': '2012-03-22T00:00:00Z',
  'time_close': '2012-03-22T23:59:59Z',
  'open': 4.81,
  'high': 4.81,
  'low': 4.81,
  'close': 4.81},
 {'time_open': '2012-03-23T00:00:00Z',
  'time_close': '2012-03-23T23:59:59Z',
  'open': 4.7,
  'high': 4.7,
  'low': 4.7,
  'close': 4.7},
 {'time_open': '2012-03-24T00:00:00Z',
  'time_close': '2012-03-24T23:59:59Z',
  'open': 4.69,
  'high': 4.69,
  'low': 4.69,
  'close': 4.69},
 {'time_open': '2012-03-25T00:00:00Z',
  'time_close': '2012-03-25T23:59:59Z',
  'open': 4.68,
  'high': 4.68,
  'low': 4.68,
  'close': 4.68},
 {'time_open': '2012-03-26T00:00:00Z',
  'time_close': '2012-03-26T23:59:59Z',
  'open': 4.55,
  'high': 4.55,
  'low': 4.55,
  'close': 4.55},
 {'time_open': '2012-03-27T00:00:00Z',
  'time_close': '2012-03-27T23:59:59Z',
  'open': 4.62,
  'high': 4.62,
  'low': 4.62,
  'close': 4.62},
 {'time_open': '2012-03-28T00:00:00Z',
  'time_close': '2012-03-28T23:59:59Z',
  'open': 4.81,
  'high': 4.81,
  'low': 4.81,
  'close': 4.81},
 {'time_open': '2012-03-29T00:00:00Z',
  'time_close': '2012-03-29T23:59:59Z',
  'open': 4.79,
  'high': 4.79,
  'low': 4.79,
  'close': 4.79},
 {'time_open': '2012-03-30T00:00:00Z',
  'time_close': '2012-03-30T23:59:59Z',
  'open': 4.81,
  'high': 4.81,
  'low': 4.81,
  'close': 4.81},
 {'time_open': '2012-03-31T00:00:00Z',
  'time_close': '2012-03-31T23:59:59Z',
  'open': 4.86,
  'high': 4.86,
  'low': 4.86,
  'close': 4.86},
 {'time_open': '2012-04-01T00:00:00Z',
  'time_close': '2012-04-01T23:59:59Z',
  'open': 4.91,
  'high': 4.91,
  'low': 4.91,
  'close': 4.91},
 {'time_open': '2012-04-02T00:00:00Z',
  'time_close': '2012-04-02T23:59:59Z',
  'open': 4.83,
  'high': 4.83,
  'low': 4.83,
  'close': 4.83},
 {'time_open': '2012-04-03T00:00:00Z',
  'time_close': '2012-04-03T23:59:59Z',
  'open': 4.97,
  'high': 4.97,
  'low': 4.97,
  'close': 4.97},
 {'time_open': '2012-04-04T00:00:00Z',
  'time_close': '2012-04-04T23:59:59Z',
  'open': 4.95,
  'high': 4.95,
  'low': 4.95,
  'close': 4.95},
 {'time_open': '2012-04-05T00:00:00Z',
  'time_close': '2012-04-05T23:59:59Z',
  'open': 4.91,
  'high': 4.91,
  'low': 4.91,
  'close': 4.91},
 {'time_open': '2012-04-06T00:00:00Z',
  'time_close': '2012-04-06T23:59:59Z',
  'open': 4.92,
  'high': 4.92,
  'low': 4.92,
  'close': 4.92},
 {'time_open': '2012-04-07T00:00:00Z',
  'time_close': '2012-04-07T23:59:59Z',
  'open': 4.95,
  'high': 4.95,
  'low': 4.95,
  'close': 4.95},
 {'time_open': '2012-04-08T00:00:00Z',
  'time_close': '2012-04-08T23:59:59Z',
  'open': 4.69,
  'high': 4.69,
  'low': 4.69,
  'close': 4.69},
 {'time_open': '2012-04-09T00:00:00Z',
  'time_close': '2012-04-09T23:59:59Z',
  'open': 4.79,
  'high': 4.79,
  'low': 4.79,
  'close': 4.79},
 {'time_open': '2012-04-10T00:00:00Z',
  'time_close': '2012-04-10T23:59:59Z',
  'open': 4.87,
  'high': 4.87,
  'low': 4.87,
  'close': 4.87},
 {'time_open': '2012-04-11T00:00:00Z',
  'time_close': '2012-04-11T23:59:59Z',
  'open': 4.84,
  'high': 4.84,
  'low': 4.84,
  'close': 4.84},
 {'time_open': '2012-04-12T00:00:00Z',
  'time_close': '2012-04-12T23:59:59Z',
  'open': 4.93,
  'high': 4.93,
  'low': 4.93,
  'close': 4.93},
 {'time_open': '2012-04-13T00:00:00Z',
  'time_close': '2012-04-13T23:59:59Z',
  'open': 4.92,
  'high': 4.92,
  'low': 4.92,
  'close': 4.92},
 {'time_open': '2012-04-14T00:00:00Z',
  'time_close': '2012-04-14T23:59:59Z',
  'open': 4.94,
  'high': 4.94,
  'low': 4.94,
  'close': 4.94},
 {'time_open': '2012-04-15T00:00:00Z',
  'time_close': '2012-04-15T23:59:59Z',
  'open': 4.96,
  'high': 4.96,
  'low': 4.96,
  'close': 4.96},
 {'time_open': '2012-04-16T00:00:00Z',
  'time_close': '2012-04-16T23:59:59Z',
  'open': 4.97,
  'high': 4.97,
  'low': 4.97,
  'close': 4.97},
 {'time_open': '2012-04-17T00:00:00Z',
  'time_close': '2012-04-17T23:59:59Z',
  'open': 4.93,
  'high': 4.93,
  'low': 4.93,
  'close': 4.93},
 {'time_open': '2012-04-18T00:00:00Z',
  'time_close': '2012-04-18T23:59:59Z',
  'open': 4.98,
  'high': 4.98,
  'low': 4.98,
  'close': 4.98},
 {'time_open': '2012-04-19T00:00:00Z',
  'time_close': '2012-04-19T23:59:59Z',
  'open': 5.12,
  'high': 5.12,
  'low': 5.12,
  'close': 5.12},
 {'time_open': '2012-04-20T00:00:00Z',
  'time_close': '2012-04-20T23:59:59Z',
  'open': 5.14,
  'high': 5.14,
  'low': 5.14,
  'close': 5.14},
 {'time_open': '2012-04-21T00:00:00Z',
  'time_close': '2012-04-21T23:59:59Z',
  'open': 5.35,
  'high': 5.35,
  'low': 5.35,
  'close': 5.35},
 {'time_open': '2012-04-22T00:00:00Z',
  'time_close': '2012-04-22T23:59:59Z',
  'open': 5.26,
  'high': 5.26,
  'low': 5.26,
  'close': 5.26},
 {'time_open': '2012-04-23T00:00:00Z',
  'time_close': '2012-04-23T23:59:59Z',
  'open': 5.2,
  'high': 5.2,
  'low': 5.2,
  'close': 5.2},
 {'time_open': '2012-04-24T00:00:00Z',
  'time_close': '2012-04-24T23:59:59Z',
  'open': 4.96,
  'high': 4.96,
  'low': 4.96,
  'close': 4.96},
 {'time_open': '2012-04-25T00:00:00Z',
  'time_close': '2012-04-25T23:59:59Z',
  'open': 5.1,
  'high': 5.1,
  'low': 5.1,
  'close': 5.1},
 {'time_open': '2012-04-26T00:00:00Z',
  'time_close': '2012-04-26T23:59:59Z',
  'open': 5.13,
  'high': 5.13,
  'low': 5.13,
  'close': 5.13},
 {'time_open': '2012-04-27T00:00:00Z',
  'time_close': '2012-04-27T23:59:59Z',
  'open': 5.1,
  'high': 5.1,
  'low': 5.1,
  'close': 5.1},
 {'time_open': '2012-04-28T00:00:00Z',
  'time_close': '2012-04-28T23:59:59Z',
  'open': 5.11,
  'high': 5.11,
  'low': 5.11,
  'close': 5.11},
 {'time_open': '2012-04-29T00:00:00Z',
  'time_close': '2012-04-29T23:59:59Z',
  'open': 4.98,
  'high': 4.98,
  'low': 4.98,
  'close': 4.98},
 {'time_open': '2012-04-30T00:00:00Z',
  'time_close': '2012-04-30T23:59:59Z',
  'open': 4.9,
  'high': 4.9,
  'low': 4.9,
  'close': 4.9},
 {'time_open': '2012-05-01T00:00:00Z',
  'time_close': '2012-05-01T23:59:59Z',
  'open': 4.95,
  'high': 4.95,
  'low': 4.95,
  'close': 4.95},
 {'time_open': '2012-05-02T00:00:00Z',
  'time_close': '2012-05-02T23:59:59Z',
  'open': 5,
  'high': 5,
  'low': 5,
  'close': 5},
 {'time_open': '2012-05-03T00:00:00Z',
  'time_close': '2012-05-03T23:59:59Z',
  'open': 5.07,
  'high': 5.07,
  'low': 5.07,
  'close': 5.07},
 {'time_open': '2012-05-04T00:00:00Z',
  'time_close': '2012-05-04T23:59:59Z',
  'open': 5.13,
  'high': 5.13,
  'low': 5.13,
  'close': 5.13},
 {'time_open': '2012-05-05T00:00:00Z',
  'time_close': '2012-05-05T23:59:59Z',
  'open': 5.07,
  'high': 5.07,
  'low': 5.07,
  'close': 5.07},
 {'time_open': '2012-05-06T00:00:00Z',
  'time_close': '2012-05-06T23:59:59Z',
  'open': 5.08,
  'high': 5.08,
  'low': 5.08,
  'close': 5.08},
 {'time_open': '2012-05-07T00:00:00Z',
  'time_close': '2012-05-07T23:59:59Z',
  'open': 5.05,
  'high': 5.05,
  'low': 5.05,
  'close': 5.05},
 {'time_open': '2012-05-08T00:00:00Z',
  'time_close': '2012-05-08T23:59:59Z',
  'open': 5.06,
  'high': 5.06,
  'low': 5.06,
  'close': 5.06},
 {'time_open': '2012-05-09T00:00:00Z',
  'time_close': '2012-05-09T23:59:59Z',
  'open': 5.05,
  'high': 5.05,
  'low': 5.05,
  'close': 5.05},
 {'time_open': '2012-05-10T00:00:00Z',
  'time_close': '2012-05-10T23:59:59Z',
  'open': 5.04,
  'high': 5.04,
  'low': 5.04,
  'close': 5.04},
 {'time_open': '2012-05-11T00:00:00Z',
  'time_close': '2012-05-11T23:59:59Z',
  'open': 4.85,
  'high': 4.85,
  'low': 4.85,
  'close': 4.85},
 {'time_open': '2012-05-12T00:00:00Z',
  'time_close': '2012-05-12T23:59:59Z',
  'open': 4.96,
  'high': 4.96,
  'low': 4.96,
  'close': 4.96},
 {'time_open': '2012-05-13T00:00:00Z',
  'time_close': '2012-05-13T23:59:59Z',
  'open': 4.95,
  'high': 4.95,
  'low': 4.95,
  'close': 4.95},
 {'time_open': '2012-05-14T00:00:00Z',
  'time_close': '2012-05-14T23:59:59Z',
  'open': 4.93,
  'high': 4.93,
  'low': 4.93,
  'close': 4.93},
 {'time_open': '2012-05-15T00:00:00Z',
  'time_close': '2012-05-15T23:59:59Z',
  'open': 5.01,
  'high': 5.01,
  'low': 5.01,
  'close': 5.01},
 {'time_open': '2012-05-16T00:00:00Z',
  'time_close': '2012-05-16T23:59:59Z',
  'open': 5.04,
  'high': 5.04,
  'low': 5.04,
  'close': 5.04},
 {'time_open': '2012-05-17T00:00:00Z',
  'time_close': '2012-05-17T23:59:59Z',
  'open': 5.09,
  'high': 5.09,
  'low': 5.09,
  'close': 5.09},
 {'time_open': '2012-05-18T00:00:00Z',
  'time_close': '2012-05-18T23:59:59Z',
  'open': 5.1,
  'high': 5.1,
  'low': 5.1,
  'close': 5.1},
 {'time_open': '2012-05-19T00:00:00Z',

5. Convert the previous object to a pandas dataframe

In [29]:
df_crypto = pd.DataFrame(first_crypto)
df_crypto

,time_open,time_close,open,high,low,close,market_cap,volume
0,2012-01-01T00:00:00Z,2012-01-01T23:59:59Z,4.720000,4.720000,4.720000,4.720000,NaN,NaN
1,2012-01-02T00:00:00Z,2012-01-02T23:59:59Z,5.270000,5.270000,5.270000,5.270000,NaN,NaN
2,2012-01-03T00:00:00Z,2012-01-03T23:59:59Z,5.220000,5.220000,5.220000,5.220000,NaN,NaN
3,2012-01-04T00:00:00Z,2012-01-04T23:59:59Z,4.880000,4.880000,4.880000,4.880000,NaN,NaN
4,2012-01-05T00:00:00Z,2012-01-05T23:59:59Z,5.570000,5.570000,5.570000,5.570000,NaN,NaN
...,...,...,...,...,...,...,...,...
3645,2021-12-27T00:00:00Z,2021-12-27T23:59:59Z,50871.136201,52040.010462,50648.783664,50805.926381,9.620695e+11,2.706242e+10
3646,2021-12-28T00:00:00Z,2021-12-28T23:59:59Z,50785.014226,50785.014226,47532.642786,47754.479284,9.604874e+11,3.441168e+10
3647,2021-12-29T00:00:00Z,2021-12-29T23:59:59Z,47686.412549,48148.756050,46457.923665,46565.851628,9.019232e+11,3.235327e+10
3648,2021-12-30T00:00:00Z,2021-12-30T23:59:59Z,46622.167212,47903.118342,46378.878022,47171.745143,8.818376e+11,2.812671e+10
3649,2021-12-31T00:00:00Z,2021-12-31T23:59:59Z,47183.140352,48511.448334,45916.621766,46387.975326,8.924835e+11,3.317851e+10

6. Now that you know how to convert one element of `crypto` into a dataframe, write ONE line of code that will convert each element into a dataframe and store them in a `list` object.

<details>
<summary>Spoiler</summary>
Use a list comprehension :)
</details>

In [43]:
crypto_list = [pd.DataFrame(crypto[coin]) for coin in crypto.keys()]
crypto_list

[                 time_open            time_close          open          high  \
 0     2012-01-01T00:00:00Z  2012-01-01T23:59:59Z      4.720000      4.720000
 1     2012-01-02T00:00:00Z  2012-01-02T23:59:59Z      5.270000      5.270000
 2     2012-01-03T00:00:00Z  2012-01-03T23:59:59Z      5.220000      5.220000
 3     2012-01-04T00:00:00Z  2012-01-04T23:59:59Z      4.880000      4.880000
 4     2012-01-05T00:00:00Z  2012-01-05T23:59:59Z      5.570000      5.570000
 ...                    ...                   ...           ...           ...
 3645  2021-12-27T00:00:00Z  2021-12-27T23:59:59Z  50871.136201  52040.010462
 3646  2021-12-28T00:00:00Z  2021-12-28T23:59:59Z  50785.014226  50785.014226
 3647  2021-12-29T00:00:00Z  2021-12-29T23:59:59Z  47686.412549  48148.756050
 3648  2021-12-30T00:00:00Z  2021-12-30T23:59:59Z  46622.167212  47903.118342
 3649  2021-12-31T00:00:00Z  2021-12-31T23:59:59Z  47183.140352  48511.448334

                low         close    market_cap        volume
 0         4.720000      4.720000           NaN           NaN
 1         5.270000      5.270000           NaN           NaN
 2         5.220000      5.220000           NaN           NaN
 3         4.880000      4.880000           NaN           NaN
 4         5.570000      5.570000           NaN           NaN
 ...            ...           ...           ...           ...
 3645  50648.783664  50805.926381  9.620695e+11  2.706242e+10
 3646  47532.642786  47754.479284  9.604874e+11  3.441168e+10
 3647  46457.923665  46565.851628  9.019232e+11  3.235327e+10
 3648  46378.878022  47171.745143  8.818376e+11  2.812671e+10
 3649  45916.621766  46387.975326  8.924835e+11  3.317851e+10

 [3650 rows x 8 columns],
                  time_open            time_close         open         high  \
 0     2015-08-07T00:00:00Z  2015-08-07T23:59:59Z     2.831620     3.536610
 1     2015-08-08T00:00:00Z  2015-08-08T23:59:59Z     2.793760     2.798810
 2     2015-08-09T00:00:00Z  2015-08-09T23:59:59Z     0.706136     0.879810
 3     2015-08-10T00:00:00Z  2015-08-10T23:59:59Z     0.713989     0.729854
 4     2015-08-11T00:00:00Z  2015-08-11T23:59:59Z     0.708087     1.131410
 ...                    ...                   ...          ...          ...
 2332  2021-12-27T00:00:00Z  2021-12-27T23:59:59Z  4073.284049  4131.588597
 2333  2021-12-28T00:00:00Z  2021-12-28T23:59:59Z  4046.213554  4046.213554
 2334  2021-12-29T00:00:00Z  2021-12-29T23:59:59Z  3804.024819  3830.231923
 2335  2021-12-30T00:00:00Z  2021-12-30T23:59:59Z  3643.597981  3769.573712
 2336  2021-12-31T00:00:00Z  2021-12-31T23:59:59Z  3716.267309  3811.340874

               low        close       volume    market_cap
 0        2.521120     2.772120       164329           NaN
 1        0.714725     0.753325       674188  1.679112e+08
 2        0.629191     0.701897       532170  4.263755e+07
 3        0.636546     0.708448       405283  4.313002e+07
 4        0.663235     1.067860      1463100  4.279654e+07
 ...           ...          ...          ...           ...
 2332  4047.243542  4048.242710  12497500658  4.843321e+11
 2333  3781.572931  3808.499243  18453534135  4.811686e+11
 2334  3636.364693  3638.991067  17752949004  4.524195e+11
 2335  3619.541098  3716.513483  12943333766  4.333892e+11
 2336  3639.835114  3685.783159  16389475260  4.420833e+11

 [2337 rows x 8 columns],
                  time_open            time_close      open      high  \
 0     2015-02-25T00:00:00Z  2015-02-25T23:59:59Z  1.210160  1.215490
 1     2015-02-26T00:00:00Z  2015-02-26T23:59:59Z  1.210420  1.212320
 2     2015-03-02T00:00:00Z  2015-03-02T23:59:59Z  0.571249  0.607890
 3     2015-03-03T00:00:00Z  2015-03-03T23:59:59Z  0.605129  0.606229
 4     2015-03-06T00:00:00Z  2015-03-06T23:59:59Z  1.000000  1.000000
 ...                    ...                   ...       ...       ...
 2490  2021-12-27T00:00:00Z  2021-12-27T23:59:59Z  1.001968  1.005405
 2491  2021-12-28T00:00:00Z  2021-12-28T23:59:59Z  1.001389  1.004234
 2492  2021-12-29T00:00:00Z  2021-12-29T23:59:59Z  1.001925  1.006389
 2493  2021-12-30T00:00:00Z  2021-12-30T23:59:59Z  1.003424  1.005493
 2494  2021-12-31T00:00:00Z  2021-12-31T23:59:59Z  1.000907  1.003557

            low     close        volume   market_cap
 0     1.209580  1.211100  5.000000e+00       304476
 1     1.194710  1.205740  5.000000e+00       304541
 2     0.568314  0.606502  3.000000e+00       143726
 3     0.604416  0.606229  3.000000e+00       152250
 4     1.000000  1.000000  9.200000e+01       251600
 ...        ...       ...           ...          ...
 2490  0.999450  1.001939  4.814001e+10  78145018608
 2491  0.997730  1.001600  6.276330e+10  78099921590
 2492  0.998511  1.003309  5.715616e+10  78300015950
 2493  0.998859  1.000157  4.646933e+10  78613134205
 2494  0.997404  1.001126  5.259972e+10  78407951575

 [2495 rows x 8 columns],
                  time_open            time_close        open        high  \
 0     2017-07-25T00:00:00Z  2017-07-25T23:59:59Z    0.115203    0.115841
 1     2017-07-26T00:00:00Z  2017-07-26T23:59:59Z    0.105893    0.109013
 2     2017-07-27T00:00:00Z  2017-07-27T23:59:59Z    0.105108    0.108479
 3     2017-07-28T00:00:00Z  2017-07-28T23:59:59Z    0.107632    0.109019
 4     2017-07-29T00:00:00Z  2017-07-29T23:59:59Z    0.104782    0.111264
 ...                    ...                   ...         ...         ...
 1615  2021-12-27T00:00:00Z  2021-12-27T23:59:59Z  547.485952  571.823284
 1616  2021-12-28T00:00:00Z  2021-12-28T23:59:59Z  564.025556  564.025556
 1617  2021-12-29T00:00:00Z  2021-12-29T23:59:59Z  535.196786  540.656633
 1618  2021-12-30T00:00:00Z  2021-12-30T23:59:59Z  512.524623  527.174662
 1619  2021-12-31T00:00:00Z  2021-12-31T23:59:59Z  518.875935  527.354883

              low       close      volume   market_cap
 0       0.101531    0.105870      145269     11520300
 1       0.099266    0.105138      200395     10589300
 2       0.100888    0.107737      344499     10510800
 3       0.101473    0.104067      342568     10763200
 4       0.101108    0.107811      340218     10478200
 ...          ...         ...         ...          ...
 1615  541.515168  564.754120  1825073830  91321285310
 1616  521.939791  536.228970  2047263532  94080110304
 1617  473.158149  511.719607  3314982477  89271438382
 1618  466.090422  518.579031  1578662794  85489695480
 1619  508.453876  512.352587  1665991439  86549101590

 [1620 rows x 8 columns],
                 time_open            time_close      open      high       low  \
 0    2019-12-14T00:00:00Z  2019-12-14T23:59:59Z  0.000696  0.000841  0.000695
 1    2019-12-15T00:00:00Z  2019-12-15T23:59:59Z  0.000712  0.004942  0.000424
 2    2019-12-16T00:00:00Z  2019-12-16T23:59:59Z  0.000429  0.000429  0.000143
 3    2019-12-17T00:00:00Z  2019-12-17T23:59:59Z  0.000266  0.000333  0.000211
 4    2019-12-18T00:00:00Z  2019-12-18T23:59:59Z  0.000244  0.000244  0.000124
 ..                    ...                   ...       ...       ...       ...
 740  2021-12-27T00:00:00Z  2021-12-27T23:59:59Z  0.288844  0.299636  0.270794
 741  2021-12-28T00:00:00Z  2021-12-28T23:59:59Z  0.298577  0.299539  0.271995
 742  2021-12-29T00:00:00Z  2021-12-29T23:59:59Z  0.289902  0.342429  0.279741
 743  2021-12-30T00:00:00Z  2021-12-30T23:59:59Z  0.331544  0.352319  0.314622
 744  2021-12-31T00:00:00Z  2021-12-31T23:59:59Z  0.315270  0.315653  0.249975

         close      volume    market_cap
 0    0.000712        12.0           NaN
 1    0.000428        51.0           NaN
 2    0.000267       125.0           NaN
 3    0.000243       168.0           NaN
 4    0.000137       168.0           NaN
 ..        ...         ...           ...
 740  0.298661  25367319.0  8.315778e+10
 741  0.289911  31415379.0  8.596795e+10
 742  0.331582  56762241.0  8.349565e+10
 743  0.314662  55804442.0  9.550490e+10
 744  0.285974  53610404.0  9.083322e+10

 [745 rows x 8 columns],
                  time_open            time_close      open      high  \
 0     2018-10-09T00:00:00Z  2018-10-09T23:59:59Z  1.008473  1.075443
 1     2018-10-10T00:00:00Z  2018-10-10T23:59:59Z  1.011840  1.095062
 2     2018-10-11T00:00:00Z  2018-10-11T23:59:59Z  1.000101  1.906198
 3     2018-10-12T00:00:00Z  2018-10-12T23:59:59Z  1.002353  1.008845
 4     2018-10-13T00:00:00Z  2018-10-13T23:59:59Z  1.007296  1.020319
 ...                    ...                   ...       ...       ...
 1174  2021-12-27T00:00:00Z  2021-12-27T23:59:59Z  1.000691  1.003919
 1175  2021-12-28T00:00:00Z  2021-12-28T23:59:59Z  0.998954  1.001794
 1176  2021-12-29T00:00:00Z  2021-12-29T23:59:59Z  1.000707  1.002804
 1177  2021-12-30T00:00:00Z  2021-12-30T23:59:59Z  1.003182  1.003182
 1178  2021-12-31T00:00:00Z  2021-12-31T23:59:59Z  1.001207  1.002627

            low     close      volume    market_cap
 0     1.007108  1.012049         564           NaN
 1     0.973850  0.999934       48186           NaN
 2     0.993621  1.002691       75027           NaN
 3     1.000110  1.007179      164305           NaN
 4     1.002156  1.003489       89738           NaN
 ...        ...       ...         ...           ...
 1174  0.999112  0.999372  2193405722  4.258789e+10
 1175  0.998101  1.000800  2622842988  4.251399e+10
 1176  0.998427  1.002804  2402790646  4.258858e+10
 1177  0.999661  1.000656  2323211747  4.269391e+10
 1178  0.998346  1.000285  2334350391  4.260986e+10

 [1179 rows x 8 columns],
                  time_open            time_close      open      high  \
 0     2017-10-01T00:00:00Z  2017-10-01T23:59:59Z  0.021678  0.032226
 1     2017-10-02T00:00:00Z  2017-10-02T23:59:59Z  0.024607  0.030088
 2     2017-10-03T00:00:00Z  2017-10-03T23:59:59Z  0.025757  0.027425
 3     2017-10-04T00:00:00Z  2017-10-04T23:59:59Z  0.020864  0.022806
 4     2017-10-05T00:00:00Z  2017-10-05T23:59:59Z  0.021951  0.022154
 ...                    ...                   ...       ...       ...
 1547  2021-12-27T00:00:00Z  2021-12-27T23:59:59Z  1.457595  1.592030
 1548  2021-12-28T00:00:00Z  2021-12-28T23:59:59Z  1.514257  1.533614
 1549  2021-12-29T00:00:00Z  2021-12-29T23:59:59Z  1.405134  1.434705
 1550  2021-12-30T00:00:00Z  2021-12-30T23:59:59Z  1.334766  1.374362
 1551  2021-12-31T00:00:00Z  2021-12-31T23:59:59Z  1.360840  1.380097

            low     close      volume    market_cap
 0     0.017354  0.024969    50068700           NaN
 1     0.019969  0.025932    57641300           NaN
 2     0.020690  0.020816    16997800  6.246501e+08
 3     0.020864  0.021931     9000050  5.409450e+08
 4     0.020859  0.021489     5562510  5.691329e+08
 ...        ...       ...         ...           ...
 1547  1.455934  1.517985  1716207341  4.876723e+10
 1548  1.389404  1.411333  1853131331  5.066299e+10
 1549  1.334515  1.334515  1211833925  4.701205e+10
 1550  1.304174  1.358590  1156576565  4.465771e+10
 1551  1.290179  1.313443  1112979507  4.553007e+10

 [1552 rows x 8 columns],
                 time_open            time_close        open        high  \
 0    2020-08-26T00:00:00Z  2020-08-26T23:59:59Z    3.614188    3.790380
 1    2020-08-27T00:00:00Z  2020-08-27T23:59:59Z    3.558479    3.854475
 2    2020-08-28T00:00:00Z  2020-08-28T23:59:59Z    3.457846    4.304559
 3    2020-08-29T00:00:00Z  2020-08-29T23:59:59Z    4.015835    4.102584
 4    2020-08-30T00:00:00Z  2020-08-30T23:59:59Z    3.965328    4.688419
 ..                    ...                   ...         ...         ...
 487  2021-12-27T00:00:00Z  2021-12-27T23:59:59Z  198.192723  204.342888
 488  2021-12-28T00:00:00Z  2021-12-28T23:59:59Z  195.811870  195.811870
 489  2021-12-29T00:00:00Z  2021-12-29T23:59:59Z  177.409854  180.564911
 490  2021-12-30T00:00:00Z  2021-12-30T23:59:59Z  170.943935  175.527798
 491  2021-12-31T00:00:00Z  2021-12-31T23:59:59Z  172.634013  177.181565

             low       close      volume   market_cap
 0      3.453380    3.558723    18828792    114706133
 1      3.298325    3.436928    17983302    113827454
 2      3.457846    4.022359    23514694    111472486
 3      3.792236    3.977288    12079357    130229641
 4      3.915448    4.430499    19517464    128591246
 ..          ...         ...         ...          ...
 487  196.070018  196.070018   918000395  54216813644
 488  177.352652  178.271934  1486151317  53565517126
 489  170.956978  171.165786  1046894667  48531534590
 490  169.109151  172.543929   745246386  46762743468
 491  168.385392  170.531060   817206397  47225074594

 [492 rows x 8 columns],
                  time_open            time_close      open      high  \
 0     2013-08-04T00:00:00Z  2013-08-04T23:59:59Z  0.005874  0.005927
 1     2013-08-05T00:00:00Z  2013-08-05T23:59:59Z  0.005875  0.005980
 2     2013-08-06T00:00:00Z  2013-08-06T23:59:59Z  0.005637  0.005661
 3     2013-08-07T00:00:00Z  2013-08-07T23:59:59Z  0.004669  0.004682
 4     2013-08-08T00:00:00Z  2013-08-08T23:59:59Z  0.004397  0.004424
 ...                    ...                   ...       ...       ...
 3065  2021-12-27T00:00:00Z  2021-12-27T23:59:59Z  0.921993  0.953514
 3066  2021-12-28T00:00:00Z  2021-12-28T23:59:59Z  0.927794  0.927794
 3067  2021-12-29T00:00:00Z  2021-12-29T23:59:59Z  0.854410  0.864331
 3068  2021-12-30T00:00:00Z  2021-12-30T23:59:59Z  0.819002  0.852322
 3069  2021-12-31T00:00:00Z  2021-12-31T23:59:59Z  0.839403  0.853315

            low     close   market_cap        volume
 0     0.005874  0.005882     45921033           NaN
 1     0.005613  0.005613     45928382           NaN
 2     0.004629  0.004680     44067568           NaN
 3     0.004333  0.004417     36503525           NaN
 4     0.004175  0.004254     34372525           NaN
 ...        ...       ...          ...           ...
 3065  0.918193  0.928712  43827810468  1.435451e+09
 3066  0.850991  0.856056  44103605031  1.671035e+09
 3067  0.816917  0.817984  40615196066  1.824047e+09
 3068  0.810999  0.838805  38932072183  1.442702e+09
 3069  0.806791  0.832379  39901817688  1.333170e+09

 [3070 rows x 8 columns],
                 time_open            time_close       open        high  \
 0    2019-08-07T00:00:00Z  2019-08-07T23:59:59Z   1.127646    1.128778
 1    2019-08-08T00:00:00Z  2019-08-08T23:59:59Z   1.115096    1.217829
 2    2019-08-09T00:00:00Z  2019-08-09T23:59:59Z   1.206603    1.286859
 3    2019-08-10T00:00:00Z  2019-08-10T23:59:59Z   1.218702    1.222372
 4    2019-08-11T00:00:00Z  2019-08-11T23:59:59Z   1.134820    1.291801
 ..                    ...                   ...        ...         ...
 872  2021-12-27T00:00:00Z  2021-12-27T23:59:59Z  99.824452  103.087448
 873  2021-12-28T00:00:00Z  2021-12-28T23:59:59Z  90.996155   93.765587
 874  2021-12-29T00:00:00Z  2021-12-29T23:59:59Z  85.376644   87.646213
 875  2021-12-30T00:00:00Z  2021-12-30T23:59:59Z  84.437408   87.663484
 876  2021-12-31T00:00:00Z  2021-12-31T23:59:59Z  84.843190   90.943075

            low      close      volume    market_cap
 0     1.083715   1.102209     1476006           NaN
 1     1.102295   1.206405     2128623           NaN
 2     1.197205   1.210934     2105015           NaN
 3     1.134877   1.134877      357374           NaN
 4     1.134820   1.274025     1015714           NaN
 ..         ...        ...         ...           ...
 872  90.565028  90.933440  1430497056  3.664818e+10
 873  83.992018  85.667709  1609387260  3.340708e+10
 874  83.060375  84.040180  1138769729  3.134401e+10
 875  81.350618  84.913288   932604409  3.099919e+10
 876  84.399064  85.534930   910883128  3.114816e+10

 [877 rows x 8 columns]]

7. For each of these dataframes add a column called `"coin"` that contains the name of the key it was associated with.

<details>
<summary>Spoiler</summary>
Use a for loop and the `zip` command to be able to loop over two iterables at once
</details>

In [45]:
for df, coin in zip(crypto_list, crypto.keys()):
    df[coin] = coin
    
crypto_list[0]

,time_open,time_close,open,high,low,close,market_cap,volume,btc-bitcoin
0,2012-01-01T00:00:00Z,2012-01-01T23:59:59Z,4.720000,4.720000,4.720000,4.720000,NaN,NaN,btc-bitcoin
1,2012-01-02T00:00:00Z,2012-01-02T23:59:59Z,5.270000,5.270000,5.270000,5.270000,NaN,NaN,btc-bitcoin
2,2012-01-03T00:00:00Z,2012-01-03T23:59:59Z,5.220000,5.220000,5.220000,5.220000,NaN,NaN,btc-bitcoin
3,2012-01-04T00:00:00Z,2012-01-04T23:59:59Z,4.880000,4.880000,4.880000,4.880000,NaN,NaN,btc-bitcoin
4,2012-01-05T00:00:00Z,2012-01-05T23:59:59Z,5.570000,5.570000,5.570000,5.570000,NaN,NaN,btc-bitcoin
...,...,...,...,...,...,...,...,...,...
3645,2021-12-27T00:00:00Z,2021-12-27T23:59:59Z,50871.136201,52040.010462,50648.783664,50805.926381,9.620695e+11,2.706242e+10,btc-bitcoin
3646,2021-12-28T00:00:00Z,2021-12-28T23:59:59Z,50785.014226,50785.014226,47532.642786,47754.479284,9.604874e+11,3.441168e+10,btc-bitcoin
3647,2021-12-29T00:00:00Z,2021-12-29T23:59:59Z,47686.412549,48148.756050,46457.923665,46565.851628,9.019232e+11,3.235327e+10,btc-bitcoin
3648,2021-12-30T00:00:00Z,2021-12-30T23:59:59Z,46622.167212,47903.118342,46378.878022,47171.745143,8.818376e+11,2.812671e+10,btc-bitcoin
3649,2021-12-31T00:00:00Z,2021-12-31T23:59:59Z,47183.140352,48511.448334,45916.621766,46387.975326,8.924835e+11,3.317851e+10,btc-bitcoin

8. Upload each of these dataframes to the folder of your choice in your s3

<details>
<summary>Spoiler</summary>
Use the pandas method `to_csv` to convert your dataframes to csv files and the appropriate command from the bucket object
</details>

In [46]:
for df, key in zip(crypto_list, crypto.keys()):
    put_object = bucket.put_object(Body=df.to_csv(index=False), Key="API et Web Scrapping/data-storage/exercise-folder/csv/{}.csv".format(key))

9. Now go to your S3 to make sure the files have been uploaded correctly!